# Site settings
title: Amber Ferrero Laub
twitter_username: rob_hinds
name: Amber Ferrero Laub

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/amberferrerolaub/

#Any buzzword skills you want to include
skills:
 - Customer Support
 - Customer Success
 - Account Management
 - Project Management
 - Onboarding
 - Training

#Work experience is required
roles:
 - title: Customer Happiness Specialist
   start: 2016
   end: Ongoing
   employer: TheraNest
   description: Responsible for onboarding, educating and supporting customers from pre-trial inquiries to subscription and beyond through chat, remote training sessions and phone calls. Guides users through initial setup and features and consults on workflows best suited to their specific needs.

Acts as the customer's liaison with the product team to pass on bug reports, unique use cases and challenges they are experiencing. Reports on support trends to assist with the planning of future product iterations.

Champions customer success by building relationships and assisting with EHR/EMR data migration projects. Nurtures large, at-risk and detractor customers. Works with existing customers to ensure retention and seamless internal transfers.

Manages support resources by writing and updating knowledge base articles, saved replies and internal support processes. Contributes to the TheraNest Facebook community. 

- title: Project Manager
   start: 2014
   end: 2016
   employer: Entermotion / Paste Interactive
   description: Managed studio design and web application development projects to ensure they were on track and on budget by prioritizing deliverables and handling the details for my team. Ensured constant communication with clients and a distributed team of designers and developers throughout multiple time zones. Provided email and phone support to assist with issues related to custom client web applications and our own SaaS products: Atlas.md, jumpchart and staction. Handled questions related to client email setup, billing and new project sales all while ensuring an exceptional customer experience.
 - title: Project Manager/Account Executive
   start: 2013
   end: 2014
   employer: First Page Sage
   description: Managed SEO campaigns and web design projects for multiple clients in a remote working environment. Collaborated with internal technical team, writing team and agency executives to best serve the needs of clients and ultimately drive web traffic. Acted as an advocate to ensure clients' goals and expectations were communicated clearly to the internal team. Ensured consistent client contact to relay campaign progress.
 - title: Assistant Account Executive
   start: 2010
   end: 2013
   employer: SK+G
   description: Coordinated the day-to-day operations and management of interactive accounts and their related web development and digital marketing projects. Served as a main contact for clients and coordinated between them and departments within the agency. Managed client expectations with regard to creative strategy executions and project timelines for initiatives. Ensured that agency jobs were opened accurately and on time and monitored work from inception to completion. Proofread all web and print client deliverables. Assisted with execution of media plans. Responsible for client website updates using content management systems. Worked closely with web development team to ensure client websites were running smoothly and issues were quickly resolved. Google Analytics reporting for interactive clients. Worked closely with interactive media team to ensure SEO of client websites and management of interactive media campaigns. Reviewed and reconciled client invoices for billing.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2003
   subject: Artificial Intelligence and Computer Science
   school: University of Birmingham

intro: Compassionate customer advocate and product specialist who loves teaching and problem solving. I specialize in helping customers understand software and processes, building relationships, and working with my team to improve user experience.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Scala</strong>: My current role uses Scala as the primary language and have been building applications in Scala for the last two years. I am familiar with a range of Scala libraries, such as <a target="_blank" href="http://automateddeveloper.blogspot.com/2017/12/an-opinionated-guide-to-building-apis.html"> Akka-Http for building microservices</a> and <a target="_blank" href="http://automateddeveloper.blogspot.com/2018/09/generic-programming-with-scala.html"> Shapeless for generic programming</a>, as well as familiar with a range of <a target="_blank" href="https://basementcrowd.com/2018/11/28/scala-the-aux-pattern-path-dependent-types/" >functional programming techniques available</a>.<br/><br/>
   <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others. <br/><br/>
   <strong>Groovy</strong> I have used Groovy as a language in production for ~4 years and I am familiar with many of the languages features (such as writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>) and quirks (such as <a target="_blank" href="https://dzone.com/articles/groovy-retrospective-an-addendum-memory-usage-perm">memory leak issues</a>). <br/><br/>
   <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, <a target="_blank" href="http://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="http://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="http://projects.spring.io/spring-social/">http://projects.spring.io/spring-social/</a>. <br/><br/>
   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="http://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
